name: CI pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📬 Send success email
        uses: dawidd6/action-send-mail@v3
        if: success()  # Only send if the workflow succeeded
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: ✅ Deployment Successful!
          to: aya.jafar002@gmail.com
          from: GitHub Actions Bot
          body: |
            Hey there!

            Your push to main was successful, and the deployment is complete.

            🎉 You’re crushing it 🚀
